from django.db.models.signals import post_save , pre_save
from django.dispatch import receiver
from .models import *
from django.conf import settings
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives

# @receiver(pre_save, sender=User)
# def just_begining(sender, instance, **kwargs):
#     print("presave signal")
#     print("sender " ,sender)
#     print("instance "   ,instance)
#     print(f"kwargs {kwargs}")


@receiver(post_save, sender=User)
def user_created(sender, instance, created, **kwargs):
    if created:
        subject = f'User created'

        text_message = f'Hello {instance.first_name},\nThank you for Registering.\nThis mail is autogenerated. Do not reply to this mail.\nRegards,\nHealthquiz Team.'
        html_content = f"<p>Hello {instance.first_name},<br>Thank you for Registering.<br>This mail is autogenerated. Do not reply to this mail.<br>Regards,<br>Healthquiz Team.</p>"
        # html_content = "<p>This is an <strong>important</strong> message.</p>"
        from_email = settings.EMAIL_HOST_USER
        to = instance.email

        print("postsave signal")
        print("sender " ,sender)    
        print("instance "   ,instance)
        print(f"kwargs {kwargs}")

        msg = EmailMultiAlternatives(subject, text_message, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        # msg.content_subtype = "text/plain"  # Main content is now text/html
        msg.attach_file('2024-05-31 15:56:58.699703_6a78b693ec884069b92dcf294585f66e.pdf')

        msg.send()
        # send_mail(
        #         subject,
        #         text_message,
        #         from_email,
        #         [to],
        #         fail_silently=False,
        #     )
    else:
        print("User not created")