# Generated by Django 5.0.6 on 2024-05-27 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('question_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(null=True)),
                ('number_of_options', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'QUESTIONS',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('quiz_title', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=50)),
                ('time_duration', models.TimeField()),
            ],
            options={
                'db_table': 'QUIZ',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('option_name', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.questions')),
            ],
            options={
                'db_table': 'OPTIONS',
            },
        ),
    ]
