# Generated by Django 5.0.6 on 2024-05-31 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizperformance',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_performance_ques', to='quiz.questions'),
        ),
        migrations.AddField(
            model_name='quizperformance',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='quiz.options'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_quiz', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizperformance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_performance', to='quiz.scheduledevent'),
        ),
    ]
