# Generated by Django 5.0.6 on 2024-05-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='createdBy',
            new_name='created_by',
        ),
    ]
