# Generated by Django 5.0.6 on 2024-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizperformance_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
