# Generated by Django 5.0.6 on 2024-05-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_scheduledevent_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizperformance',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='is_archived',
        ),
    ]
