# Generated by Django 5.0.6 on 2024-05-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('DOCTOR', 'Doctor')], default='USER', max_length=50),
        ),
    ]
