# Generated by Django 5.0.6 on 2024-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default='2024-05-27 04:33:58.728887'),
            preserve_default=False,
        ),
    ]
