# Generated by Django 5.0.6 on 2024-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('DOCTOR', 'Doctor')], max_length=50),
        ),
    ]
